### ISSUE TITLE
Cableado del auto

### ISSUE THREAD

**Issue by joseOrduno** [tectijuana/Interfaz15WikiRPI#53]
Se conectarán los motores a la motor Shield y la motor Shield a la raspberry pi @ferminreyes @Joel13 @ZunigaGabriel

**Comment by ZunigaGabriel** [comment]
En teoría ya funciona, solo necesitaremos realizar modificaciones o bien, realizar la conexión por medio de SSH. 
@joseOrduno , @ferminreyes  , @Joel13
